"""
apps/appointments/models.py
Appointment scheduling models — implements FR-02.
"""
from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone
from datetime import timedelta


class Appointment(models.Model):
    """
    Central transactional entity for MediConnect.
    Implements FR-02.1 through FR-02.7.

    The status CHECK constraint encodes the appointment lifecycle
    state machine directly at the model layer, enforced by Django
    validators and mirrored in the PostgreSQL CHECK constraint
    generated by the migration.
    """
    class Status(models.TextChoices):
        PENDING   = 'pending',   'Pending'
        CONFIRMED = 'confirmed', 'Confirmed'
        COMPLETED = 'completed', 'Completed'
        CANCELLED = 'cancelled', 'Cancelled'
        NO_SHOW   = 'no_show',   'No Show'

    patient      = models.ForeignKey(
        'accounts.User', on_delete=models.CASCADE,
        related_name='patient_appointments',
        limit_choices_to={'role': 'patient'}
    )
    doctor       = models.ForeignKey(
        'accounts.DoctorProfile', on_delete=models.CASCADE,
        related_name='appointments'
    )
    scheduled_at  = models.DateTimeField()
    duration_mins = models.PositiveIntegerField(default=30)
    status        = models.CharField(
        max_length=20, choices=Status.choices, default=Status.PENDING
    )
    reason        = models.TextField(blank=True)
    doctor_notes  = models.TextField(blank=True)
    reminder_sent_24h = models.BooleanField(default=False)
    reminder_sent_2h  = models.BooleanField(default=False)
    created_at    = models.DateTimeField(auto_now_add=True)
    updated_at    = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'appointments'
        ordering = ['-scheduled_at']
        indexes  = [
            models.Index(fields=['doctor', 'scheduled_at']),
            models.Index(fields=['patient', 'scheduled_at']),
            models.Index(fields=['status']),
        ]

    def __str__(self):
        return (
            f"Appt #{self.id} — {self.patient.full_name} "
            f"with Dr. {self.doctor.user.full_name} at {self.scheduled_at}"
        )

    def clean(self):
        """
        Conflict detection (FR-02.3): prevent double-booking by
        checking for overlapping appointments for the same doctor.
        """
        if not self.scheduled_at or not self.doctor_id:
            return

        end_time = self.scheduled_at + timedelta(minutes=self.duration_mins)

        conflicts = Appointment.objects.filter(
            doctor=self.doctor,
            status__in=[self.Status.PENDING, self.Status.CONFIRMED],
            scheduled_at__lt=end_time,
            scheduled_at__gte=self.scheduled_at - timedelta(minutes=self.duration_mins or 30)
        )

        # Exclude self when updating
        if self.pk:
            conflicts = conflicts.exclude(pk=self.pk)

        if conflicts.exists():
            raise ValidationError(
                f"Dr. {self.doctor.user.full_name} already has an appointment "
                f"at {self.scheduled_at.strftime('%d %b %Y %H:%M')}. "
                f"Please choose a different time slot."
            )

    def save(self, *args, **kwargs):
        self.full_clean()  # Run clean() on every save
        is_new = self.pk is None
        super().save(*args, **kwargs)

        # Trigger notifications after save for new appointments
        if is_new:
            from apps.notifications.tasks import send_appointment_confirmation
            send_appointment_confirmation.delay(self.id)

    @property
    def end_time(self):
        return self.scheduled_at + timedelta(minutes=self.duration_mins)

    @property
    def is_upcoming(self):
        return self.scheduled_at > timezone.now() and self.status in (
            self.Status.PENDING, self.Status.CONFIRMED
        )

    def can_be_cancelled(self):
        """Allow cancellation up to 2 hours before the appointment."""
        return (
            self.status in (self.Status.PENDING, self.Status.CONFIRMED) and
            self.scheduled_at > timezone.now() + timedelta(hours=2)
        )


class DoctorReview(models.Model):
    """
    Patient reviews of completed doctor appointments.
    Rating feeds into DoctorProfile.rating via update_rating().
    """
    appointment = models.OneToOneField(
        Appointment, on_delete=models.CASCADE, related_name='review'
    )
    patient = models.ForeignKey(
        'accounts.User', on_delete=models.CASCADE, related_name='reviews_given'
    )
    doctor = models.ForeignKey(
        'accounts.DoctorProfile', on_delete=models.CASCADE, related_name='reviews'
    )
    rating  = models.PositiveSmallIntegerField(
        choices=[(i, str(i)) for i in range(1, 6)]
    )
    comment    = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'doctor_reviews'
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # Recalculate doctor's average rating
        self.doctor.update_rating()

    def __str__(self):
        return f"Review by {self.patient.full_name} for Dr. {self.doctor.user.full_name} — {self.rating}/5"

