---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mediconnect-aws-secrets
  namespace: mediconnect
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgDzFQ0ff3MjabEw8EDo+6b86gJYryl61l8E9aunk5W6ktJNlM91il1xO3S1vbczx7v2Ch4IxV4kr4JfaXxpitQ6/Qe7xUHo68jCcJ02CeVMU3t7v3c0HjTYl4dU0U/TKTuslkVP9SfXY0R672CY4z2nLqRZJGOCYlk9vpB6Vq1B2ZhVu1WFqDePGKlZoR5NMYzG05FSo7fFTl78fp4O2fQjgxaALMU9AgSJWmFmEzbK2JHnUQMMB4vHYIsJAGYih8M9OJ5OHp38YGGZ5RxmjQRU50+ciMbFaKyFZxgP7mpskwN9BhEBNaHvQ0jmt5q4Dwst8BC0NAkkrh4oBEmJ4mrsIsvZUfIj9WksmPpRRHH+KogQ9FdkPyIrNmdei3XzntrRd8HElKaiGaJ0qM2LJP57ewwqAc8QvXFnSj+gCQOtGQkB2a9KkfNNxu2Mg6HSMsE+uPtyMtqvXw7ajF4ox2+YWUo6BT6Y10A2FYVw6m+qmEyHmqmhzQQvTlZm2wejBkPbyIn60B0uM+XR6KYtFPckSEkN1LiUb7ggtq78Xq8DR6B3nG//oOpCPW/gOJReHOw0z1FMNbjfZVuq9uI++muDFS50GHsMTtRS7wZfMzPrAV/S/QoJQzwA5+sp45KKMANW9VyM3iUKl4/rJycNm4bumHCJcw8+tYy80NOMlbalI2JmooFCimMVCTZigRQEK6aorq6P+f6PrW7FRqUHZRxlsnh6MQ==
    AWS_SECRET_ACCESS_KEY: AgA6Z0D2LfkeexfNQVhhuzw1i6UzrlQSMd5MiXerntXJbdVLEl4fSzKtyxvohHi9wJjoFvpkGCq2dM+75XGj859Izxh77XCCc2ZjqyteO1k4mPgmLlbfHr2lUcYpeid81+K7KaadEKRmnSmBWhZqtyujr+bf0laXzxvKubKRTXPDCEu6X0WWp1636anp9V/JjGUTLYKi5L+W+FIN0MOOeKuRXLbHZAm15LSq2KhBv/5r9s72ijncDWlzA6McWonc85RcHnNrLWksu8W4U95I+ZA+5ZD2VXCKVT+ZF8eP8h3ocmcOPcaf8nVVwAt56IQZkdgVbGAPGl0kFooyPlfkmTSxUhfdzGob0/1RavzERhmAcSwQHE28hgCecmIjPqVY1gBfkRCbglTFJb34tXERdOzNRJXctbZ0fTSjVpPZTA8o3xBuy0cQSZ2A6Z2rulCe/GbeIARHAzldvdMZ62agsTvWE90rgYGTFflVDg98gKu1Pc73e7SDD7pEn2ESOsia7926zYkIGNUG693KhlPIB0vb2Zd1Vi+KhVTRLrWkJHm+nrUNHyvwT183XKMSpNJwmaGv/IsIdyquQEfqB1RiyOmEJErJ8xaIdz+O9sQscUy3CGR3Z5yhzsgBO61xKW+QqTHSRKzw6L69XT8QeSfydmKZbwODctqFNCqofdKtdUk7Sw73e9+HvEBEtRFgkbP31g6fVgdT1f5XHYGcSeYcyWm1Usvg/bZFSTCq4zdFmDPA5h1c4wbOfxjj
  template:
    metadata:
      name: mediconnect-aws-secrets
      namespace: mediconnect
