---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mediconnect-aws-secrets
  namespace: mediconnect
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBvtYH7LbbLD8pvg+tr5usJbetCz1NKH1jRy2WaAdv5NtIfyvINNFf9GSVYv2jHMydDdaxjgqvOGoidcL/mxML37OeLcH8rdG/YWRsuCUgdLchXiaAqu8dRlt5fVDFvAjGVsS1Px0/L5yQx1ruBbDDp5C3Wt5XNrgcEVfcrxp9VGFyw6zhrf8NP+liJosHMSg7Dd2LHagTtVfXLEGAinGsnctwu/iqimKATU+5otJ6eLHMbnJSmq5oJo5CJMJl3QDzvmQYAuJZiMA8iMQ6Pdr2CF9w4awqASi/a7zNurXJWCiNKfvC2SU9KolAKd363mTt+K0/UzL5yIkwGQajHzT+951cYm3sKKA1axOgNVRZKT0PldwL/BvcPV8f7uIGOj86ijMUppY/dIhxfvA0/Eg0/41R1n6mW2U4wC+b1ThzRo6omZmEKQpl2Lh2NGa2At74I/c6kWBem528Nna96Oqq6ruice5vWopt9L+IezSkHWTE4YylBy/hIm7i+/sQcUE1H48XSWw7Sv2JhCCrSI9O54MsNbVXal3GyjJJ0QotBHmY62IRSpJbmzx2nAtNtUv6epBoHGNLYDMNwo6Z7fcWClq1vMYTI7T4UcVcm6u3lP8s5sOcwA02K2cK0vzNxa3a+68x+qGnaWad0Gdr6mwsaakH7qQJc1f0qdF2zW/2TbjX9lAoCeeL9Ey85mtcZr1YXe82+TbJS99+E6AhkUOGz0IdYPQ==
    AWS_SECRET_ACCESS_KEY: AgC5q5IPaWqiz2+XmtOFSzd5k9thIEShuhACziU6+iEO0S0j7G+Q6cPF6og7sd9XAQqdPOukQmAEyeVO2X5BNsf9C5r8tvAjVW9OgzyIqx1arTG4kXtqVqsjgquZnAweIhX3mAm8JxCmgYxFTcIgGr3p5vcv6/YldH6DHGlkCay7rj/YukfKEHhAtnM3HBVZgHL6UstquKF4bUFOBt2yxT0lJr+hFnmRLBlqpX+qVGg9emjq/7u5QBU9de11TbkqKNfjoY235tgi51MuIO57vzxZgKvgBdsAZOXwJgZATSzrfJCoYknpoNws2FQeJReHWlbUzaxg08vVmuggox8JsA+oj0OQwm6JdfZR4/8LU9uXKW9g6dy76EO7rmX1eELeMBHddKPQWrqpmeOveP4HRRUux0ujd6yp0Z3+7dmZeruJS0RPkk6JccJ8PvSlh8IC2lD24Zgpbc9IJEwzSaPBOj+H1wnW6rgGbAQW7WVtN+8Yt1KJIM1sB5axUkFdN6ycAJ3xkkKKARCKkNFJ1aZuL4BpdZkK2RE1DJCWfvrnPQvIdNKt6F+SVxzIeZD6hpkyXLDLdSbCs7FOKEV8ipjWDgjnrgcKMO/OwJYk+CYHQ39Jnl071BrsqzuhJ1Q4h6sntAboqrm19257HaNQJzNpYYccSfICdUK6fIh6QDwdf0+ccuZ6rp6dkRNOde+33TvceKU4JRguhRCmgg6rKLD+ojtU85DxFP9xyBIRbf8YisrCdB1NW87p5eDE
  template:
    metadata:
      name: mediconnect-aws-secrets
      namespace: mediconnect
