---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mediconnect-aws-secrets
  namespace: mediconnect
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBiezATKQmBHABf8WaHAAwpxkIvDhJdIlaBeQ7wLS0KzRsH/8YBL6cbeTn2ZXWOq/gblGANSH5PvYsgMFPryQpB4dvTJk+DgqYhgu+Ub1WIvxMsQ/TlTD3hzKfmk09DIiRt5eWK69ENG5xHpznqFypumZMIgO745HFqtJ/FOveTQLOgSSWxDwKa5HI7VykoX9uX3s70nBwQstTVQi0cPQjZMJajASYXQ0s+4B+AOX+AGABkqxLKJH5uSrBN9AP/1d5b+lfvslZYstNmRMLc5rSlzJH6wa5UgNYUR29fzrXQVqUH8vyTS2Jx1DJtYS2fy9H+baIMIAIEexm6CzJ6D7UCWD8x+HFCHapYZX2VnowaGupZvWeXlhiaOZTN74u9noQzKEdgdHjx/bfChn9GWLYvrR7RXq7GJhMU55UFKnJ8zBoenM2XWVce9I05k8GrvjBy7KQh8MTJc9Z8TXRE+wnesuw3AvoGASlY92lDm6otwxanaGC7I5Ln429T+9c8lwWRsGsOdJPzz6NfsD2Ib5YQ1/l47oJCAFMk443NCA7ajP2c9GuFiQOICHn/a+NmkXsBA4go81JCnpCynCmv/1Jrer1rzbuxvloeQs+zzUgCUPR01P3vdgvzbHeGcmEqEcz/JZn+aAxe45UowX8m4FKYUUaO+KVv/YLBmijRVml6c/5Abuomygs7sgahbmzFnLZMW19ntFzv557Ul/zW6kAh7U3XzDb/c8XnicIZpw==
    AWS_SECRET_ACCESS_KEY: AgDStm8QDavDZE0bc4HwyvB8gdWLPCS4Q7eylJuAPD7W0WMVqobrhq7FN2CNh823SLngD5/oUixm7XhrU3U6ewcU1Af+tM340z96OJ//trBGA7ELa3O+Wysj2yKL1gOtndJtPD/paN3aoH/ZhGSQey7rVpJ0FS2NTf4vhRcs/6l6UMx3IZR/0QY71DX+xHGFLynXAd1/yUDWwPvp2Ze12sWzx82ljRqNcZQdo3devotMU26Z4fcCfYTpiQJJnV0hP2XfjRToUVrG2dtUwvbanPwdGlpyYpt/eNWyc3/72rHDUbvWnuBKanbgTb05/mBlOZ8nNyMjYOxXo6rUzwIiTwtMipUi9cO9iFsFTVWVLPVwiMHEwTuY4MLr1i+nBm6V23vBJynLI5cBRsRr0ODubspBfYrlRfXGIWCPJK6Z2lG8rkXFXROwwxzBpkfwfr+GxsK/vlJ5rgJJtI24N9N0fjK1SC5fVIC0hNUgwogP62RCYG3iHexWSvYUc/6s8Uggq9qLX5MiFe6tX2yBj3pLLg6rJkFJtoMbyElgkRDevb15FDJs8VVdEwPwmf29bqSAKCaI4f/CrDOB9SmbH8ckswTIN5/gUx+vdNU1jUsYqhLa3V1PaKAigd2Z9yAmyLYRTtlsP4+Nn2KHOVU8Z/i9JhLp+4I2VGYhuW1dpvSL8adjW90e4fjAVsSgC9/3zKXS8Ye82VyUlq9aOiueobQuEHQb3mQyTT6j5bTmVFy+5A==
  template:
    metadata:
      name: mediconnect-aws-secrets
      namespace: mediconnect
