---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mediconnect-db-credentials
  namespace: mediconnect
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgDtdKQFnbe9SKb5aJIg/clkNC6tJPQkT66m670XWVsfJvzBT5/+QrU32cUXTUniZABGF8N3rwX/qvywuVOecL++MqpfjsxTXe5hcy4Ft5XJAFrZQpMwPz8FQUUMmoK9FLrKStIsdZVXgk02LG01xWQEqJvAuP87yeLYWc5eGsN6va1Xstf8RyNvMExtmudhK/fsPa08gMCuAiMO45Fz4UiEait5IrwVNi3nMwI0oCgnv11bP2FXdTF2bRfcqRR/E3ywDXtTGVYnUDYsMy2J36CgmK6bH2hfyS6S1lluFhmWYXveY/eJKjBR1By2TZUnzaTNX1/AP5z7KSuFkIym9kVdJl1GOwqpeK83z3hwxLzFod9lYzzrC6c2Vz9S83p9SZ2SINtAhj5/6IXT1bcwqTEDIhwWNNvlkpAHd/EtK+x84BNQK49sVMabiiF9fgidFwdSLlPWRH09AyRpPqk/CuQI6fBRtlsak+DeiSCMzkJ6GZuAhGT5emnHgGnw+91RVgg7Mk+vYI/eTMouw1S7jQmicisubuBXiU8KgwjRlBi2Xy5IaDTL++ta/tR2/PeOWG7MtYKd0CslDpDp5PqGQQenY1G5bNz9s3Vhdlk8mze5satRYBCWFN7QernYGXuskKWdvBTxlMgmKZMDLHmi2JBOLIbDjZzjlpctlG0TU99EA6dssnA/JihkY6e3M3TObA+n2UZo5u3LJ4B1l1Xo3E4uQWuARFFUwTNLEwgt
  template:
    metadata:
      name: mediconnect-db-credentials
      namespace: mediconnect
