---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mediconnect-db-credentials
  namespace: mediconnect
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCUyCLXbwJUUjSCVQWhqtnCTvSarttSIsT3HrahKghJEIlKFnGrRVeFKYl31TPGC9NTQKkOVtDaXuwvtbouTKlEto3ip1IHigiebCWoBxZQMcrT03klO1HksSEymRe+LFfGKhWY3+VW4E+Msr/C+9EcDDcM2u9GUkxtg+t4jWOBZrrXz5KzSCJVfWV4tdnCE7BvBokZEQyzfQO6vs1k2sbiA/T2igWHVOCbLbPOfKVbspApdXsm9+ZfdRv5tYPAdofGsg/JeTmGhppeLQLYuutyE21DF3pf8oeLnO91BVzZYTnIlc28DsHc1n4TeRSV7ANd144zjZDxQwcDpeh7s2MihcevMx/ynozam4hEwzQ2C19L/bnvxoBb3KxVId9qgBe8EQlaY/S3dLa1GBTbc5vWOZeISt9uNjow8PsOCIj5ccn0GVC+eqQIvvSP6JztGov7o7l2lEljcHEZjKrQ/yaNd9tB/1ieMZlqP3fDsowSwqtZCQeA3YI5Hb77xGN47XUFPmLf+ijo8wWk1iH5Lgd/rMwH0rR+Vv5YNWVP9Fwk/mMe9rwVLRcuV3Ye9MYeuS4xRHp8vyV/8LlscwExcjSnlxOfTePEp5Vpl1OZXlv5b5kS6EVjidPGHprK26Sg1X2GHPuruP2thjZ54cYcdAUz0nm0+Jo16uIgMnVUo7kJVbjK3CO0A0STDkwZ1PoGGnvu/j7AfHmNkuTJeecPdG92TS9ZaPBtDCEOf5WEUAg=
  template:
    metadata:
      name: mediconnect-db-credentials
      namespace: mediconnect
