---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin_password: AgAArTzofaRpzxIJ4pSYtrc1O2UQjTWU0Jdeh7Jatkx0s42ZBdwEGE/GjhFpuKxTfFOltyTOVtrJXOFtUSzFnacBvT4Ndpe/z8/AENXdzh+qsE9HvoXqwF7quzoPazpRSnf73HdXDxP0S3anKoKAPrQFniJBXb/IFVTZguPfBra/8xoM+IueHFlwAU5QrVGKeLI3QaAcaMiXmLdxAJ54qNLO7So/Lp77oqAH8P1Ksyj15DYb5+9+xOgfTxMrKLLJISNLJfS10LquH07I4X9aXUBDTod7ZT+HdAHK43pENRHSrAFEQ4s5kZizP3vpzNW+K9nfIXCiZfYUusfkFOqAjtLh1MV3f3XmYvHWQqxc22mAj6N5Li0Kvt75STnVF/6HtKorDzURT0P3twY4nCoOJ4ikAqIgTieLsidjrpW1GFETtp77UKnsGKxqdQCw/BRXiSQUY+RIS0Bm5pLm+a7pWG+qG/1QkELuviV/LlAq/IzeGpXomrNR+sW1u5Smnc9k7o89SafBFy9p9icOpca/Zj8HGBX8VnQSRHoJUxslLvQ4VCpIhgpEL1Frq3uuuzh4YS8aDUru77EhGU21waVXBBOmJCy2FQRoTOOdr0UYtXDJ0UeHL431eaVvGF3WbyOl5w1zZOI9TCNnpaXuA7pohv8Bcxx+8kSCthuBH5V127Y/E4tzu/2xZ4mAgZQi4d67NjvTqqejKKF0X7+krTXgZM+NS4/g7xndGVA=
  template:
    metadata:
      name: grafana-secrets
      namespace: monitoring
